SELECT_CRUISE_DRP = 'cruise-drpdown'
SELECT_STATION_DRP = 'station-drpdwn'
SCATTER_PLOT_ID = 'scatter-plot-point'
SCATTER_PLOT_LINE_ID = 'scatter-plot-line'
PLOT_BGCOLOR = '#3B4758'
HEADER_BGCOLOR = '#3B4758'
CONTAINER_BGCOLOR = '#161B21'
FONT_COLOR = "#FFFFFF"
FONT_FAMILY = "Roboto, Helvetica, Arial, sans-serif"