COLLECTION_TEMPLATE = 'collection_drp_option_{0}'
SCATTER_PLOT_ID = 'scatter-plot-point'
SCATTER_PLOT_LINE_ID = 'scatter-plot-line'
PLOT_BGCOLOR = '#3B4758'
HEADER_BGCOLOR = '#3B4758'
CONTAINER_BGCOLOR = '#161B21'
FONT_COLOR = "#FFFFFF"
FONT_FAMILY = "Roboto, Helvetica, Arial, sans-serif"
FONT_SIZE_NUMBER = '25px'
FONT_SIZE = 'x-large'
GENERAL_STORE_ID = "general"
GROUPS_SECTION = "groups"
GROUP = "group"
MAIN_GROUP = "main_group"
SCATTER_FONT_SIZE = '18'
