name: doors
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.8
  #Required
  - dash
  - pip
  - plotly
  - xcube >=1.3.0
  - xcube_geodb
  - waitress
  - pip:
    - dash-material-ui
