id: bg1
title: Bulgaria MAFs
eez: BG_eez
features:
  - id: bulgaria_ports_points
    type: local
    params:
      file: "../../data/locations/bulgaria_ports_points.csv"
      label: label
components:
  scattermap:
    scattermap:
      placement: left
  meteogram:
    meteogram_selection:
      placement: top
    meteogram_image:
      placement: right
