id: bgfml
title: Bulgaria Floating Marine Litter
eez: BG_eez
features:
  - id: BG_FML_2016-2018
    type: geodb
    params:
      title: "Bulgaria FML 2016-2018"
      collection: BG_FML_2016-2018
      database: io-bas
      color: green
      variables:
        - "floating marine litter density (c) item/km2"
      colorcodevariable:
        name: "floating marine litter density (c) item/km2"
        color_min_value: 0
        color_max_value: 400
        color_range: dense
  - id: bulgaria_natura_points
    type: local
    params:
      file: "../../data/collections/Natura2000_Areas_Bulgaria/Natura2000_Areas_Bulgaria.shp"
  - id: bulgaria_bathing_water_points
    type: local
    params:
      file: "../../data/collections/bathing_waters_bulgaria/bathing_waters_bulgaria.shp"
  - id: bulgaria_shellfish_points
    type: local
    params:
      file: "../../data/collections/Shellfish_Production_BG/shellfishPoint.shp"
components:
  scattermap:
    scattermap:
      placement: left
      background_variable: sst
  selectcollection:
    selectcollection:
     placement: top
description: "This dashboard is about the floating marine litter data for the black 
sea"