id: bgmmaps
title: Bulgaria MAF Map
eez: BG_eez
features:
  - id: BG_FML_2016-2018
    type: geodb
    params:
      title: "Bulgaria FML 2016-2018"
      collection: BG_FML_2016-2018
      database: io-bas
      color: green
      variables:
        - "floating marine litter density (c) item/km2"
      colorcodevariable:
        name: "floating marine litter density (c) item/km2"
        color_min_value: 0
        color_max_value: 400
        color_range: Oranges
components:
  scattermap:
    scattermap:
      placement: left
  selectcollection:
    selectcollection:
     placement: top