id: ge1
title: Georgia Emblas
eez: GE_eez
features:
  - id: EMBLAS_Nutrients_2016_2019
    type: geodb
    params:
      title: EMBLAS Nutrients 2016-2019
      collection: EMBLAS_Nutrients_2016_2019
      database: water-quality
      color: red
      levels:
        - "cruise"
        - "station"
        - "sampling depth [m]"
      label: station
      convert_from_parameters:
        keys:
          - "station"
          - "sampling depth [m]"
        value: "value"
        parameter: "parameter"
      variables:
        - "Ammonia nitrogen"
        - "Nitrate nitrogen"
        - "Nitrite nitrogen"
        - "Phosphate"
        - "Silicon"
        - "Total nitrogen"
        - "Total phosphorus"
  - id: EMBLAS_Physics_2016_2019
    type: geodb
    params:
      title: EMBLAS Physics 2016-2019
      collection: EMBLAS_Physics_2016_2019
      database: water-quality
      color: blue
      levels:
        - "cruise"
        - "station"
        - "sampling depth [m]"
      label: station
      variables:
        - "salinity [psu]"
        - "temperature [°c]"
        - "sampling depth [m]"
  - id: EMBLAS_CHL_2016_2019
    type: geodb
    params:
      title: EMBLAS Chlorophyll 2016-2019
      collection: EMBLAS_CHL_2016_2019
      database: water-quality
      color: green
      levels:
        - "cruise"
        - "station"
        - "sampling depth [m]"
      label: station
      variables:
        - "chl-a [mg/m3]"
components:
  scattermap:
    scattermap:
      placement: left
  selectcollection:
    selectcollection:
     placement: top
  scatterplot:
    scatterplot:
      placement: right
