id: ge4
title: Georgia Floating Marine Litter
eez: GE_eez
features:
  - id: Floating_Marine_Litter_Cruise_3
    type: geodb
    params:
      title: Aerosol Optical Thickness Cruise 3
      collection: Floating_Marine_Litter
      database: DOORS_Cruise_3_IO-BAS
      variables:
        - "transect"
        - "concentration of macro plastic (items/km^2)"
      colorcodevariable:
        name: "concentration of macro plastic (items/km^2)"
        color_min_value: 160
        color_max_value: 2940
        color_range: Oranges
components:
  scattermap:
    scattermap:
      placement: left
  selectcollection:
    selectcollection:
     placement: top
description: It shows the floating marine litter data for Georgia region from database
  of DOORS Cruise 3 IO-BAS.
