id: ro1
title: Romania MAF
eez: RO_eez
features:
  - id: Phytoplankton
    type: geodb
    params:
      title: Phytoplankton
      collection: Phytoplankton
      database: DOORS_Cruise_1_IO-BAS
      levels:
        - "station"
        - "sampling depth [m]"
      label: station
      variables:
        - "acanthoica sp. n[cells/l]"
        - "calyptrosphaera oblonga n[cells/l]"
        - "coccolithus sp.3 (18) n[cells/l]"
        - "coronosphaera mediterranea n[cells/l]"
        - "emiliania huxleyi n[cells/l]"
        - "acanthoica sp. b[mg/m^3]"
        - "calyptrosphaera oblonga  b[mg/m^3]"
        - "coccolithus sp.3 (18)  b[mg/m^3]"
        - "coronosphaera mediterranea b[mg/m^3]"
        - "emiliania huxleyi  b[mg/m^3]"
  - id: Chlorophyll-a_and_TSM_Cruise_1
    type: geodb
    params:
      title: Chlorophyll-a_and_TSM Cruise 1
      collection: Chlorophyll-a_and_TSM
      database: DOORS_Cruise_1_IO-BAS
      levels:
        - "station"
        - "sampling depth [m]"
      label: station
      variables:
        - "chl-a [mg/m3]"
        - "tsm  [mg/l]"
        - "secchi disk [m]"
        - "temperature [째c]"
        - "salinity [psu]"
        - "air temperature [째c]"
        - "wind speed [m/s]"
  - id: Chlorophyll-a_and_TSM_Cruise_2
    type: geodb
    params:
      title: Chlorophyll-a and TSM Cruise 2
      collection: Chlorophyll-a_and_TSM
      database: DOORS_Cruise_2_Leg_1_IO-BAS
      levels:
        - "station"
        - "sampling depth [m]"
      label: station
      variables:
        - "chl-a [mg/m3]"
        - "tsm [mg/l]"
        - "secchi disk [m]"
        - "temperature [째c]"
        - "salinity [psu]"
        - "air temperature [째c]"
        - "wind speed [m/s]"
        - "ap [hpa]"

components:
  scattermap:
    scattermap:
      placement: left
  selectcollection:
    selectcollection:
     placement: top
  scatterplot:
    scatterplot:
      placement: right
