id: upcfml
title: Marine Litter Trajectories
features:
  - id: marine_litter_trajectory_40
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_40.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 40
    type: local
  - id: marine_litter_trajectory_41
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_41.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 41
    type: local
  - id: marine_litter_trajectory_42
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_42.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 42
    type: local
  - id: marine_litter_trajectory_43
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_43.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 43
    type: local
  - id: marine_litter_trajectory_44
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_44.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 44
    type: local
  - id: marine_litter_trajectory_45
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_45.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 45
    type: local
  - id: marine_litter_trajectory_46
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_46.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 46
    type: local
  - id: marine_litter_trajectory_47
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_47.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 47
    type: local
  - id: marine_litter_trajectory_48
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_48.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 48
    type: local
  - id: marine_litter_trajectory_49
    params:
      color: red
      file: ../../data/collections/upc_marine_litter_trajectory_49.csv
      label: trajectory
      mapmode:
        mode: lines
      title: Trajectory 49
    type: local
components:
  scattermap:
    scattermap:
      placement: left
  selectcollection:
    selectcollection:
     placement: top